# Generated by Django 5.0 on 2025-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="reminder_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
